graph TD

ATS

Screening

HR

Technical

Behavior

Integrity

Decision

ATS --> Decision

Screening --> Decision

HR --> Decision

Technical --> Decision

Behavior --> Decision

Integrity --> Decision