flowchart TD

A[Resume Upload]

B[Resume Parser]

C[ATS Engine]

D[Screening AI]

E[HR Interview AI]

F[Technical Interview AI]

G[Behavior Analysis]

H[Integrity Detection]

I[Decision AI]

J[Hiring Report]

A --> B
B --> C
C --> D
D --> E
E --> F
F --> G
G --> H
H --> I
I --> J